controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_default:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /fr
        permanent: true
register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [GET]
    defaults:
        _locale: '%kernel.default_locale%'
    requirements:
        _locale: 'en|fr|ar'        